use_frameworks!

platform :ios, '10.0'

target 'Mylib_Example' do
  pod 'Mylib', :path => '../'

#  target 'Mylib_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
